language: ruby
branches:
  only:
    - main
before_script:
  - chmod +x deploy.sh
script:
  - bundle exec jekyll build
  - "./deploy.sh"
env:
  global:
    secure: "z0sAp2ODca+OcbNkcqrloAub2/0pHPWKOKIzhGzNW9s3tRZo0sC05qQrLSX4cYKwmeca5CZkoJTxOm9NwlJl+Lbvg+E4BqBsyMYXtK9lcONHcoRIV3wbo7UirPrBrhqsDr7Gi3qw6w7CMKSDDiPhZGv7IIA+f+svKNlKK1Fnq57HnBll2DCI/lD9/troLzfDge4gXFsBECweyQCEGE+isSzdAO3Rfausyxl7ZUT0MKx7j1TBb+FrTX/z2W3r3JLkr1moF+rEulz+X9bL+QVVATZdEdy/c6uiagoArbZoo69joaOS67t7xzUma9FLXc1D+Y8NSiWyaW/ln06Tt8XJsOf3fLAp2owciAKRWAgRxLpK6FwyOVosXTBw1SkbN0whrgoJrJORX8BLXHod441KkJXJkQX7mMY4+a7OSIbg0IEM1vF2U7j2fZx+TqDpTh4q46ljkq4wMutjm/Z+pMjuXr83KIqp+u1hGNh3LMCihv/TIO5fX+SdTLbp+3ojvCZGM3VF+DJYoloWimBbWBXIkuQjCDzHsFd2H0gzrqt/oDFrSx0xxxrUcNZj60Fnj6GUGYKCjUDEp6xdMIvCqNinEPslJCkAs6JkATmYtCBav7zzSfCzKEY5bKTOCFVhMQ9NKo6vvNGmjQSirD/MmyecetvWyFr3/Ggc/uDil6kgwt4="