language: ruby
branches:
  only:
    - main
before_script:
  - chmod +x deploy.sh
script:
  - bundle exec jekyll build
  - "./deploy.sh"
env:
  global:
    secure: "gGypIrEHTV2XUJJTDK1tjN30p/Q4bny6nuaPDfU6bz146sj+f4nAjVWg18IgFYsmxXAQorEMl0KQLNK8eBpBA5cF7UQBY/Y5FLrTGqOmDLMMvexFxZhn4aro3Rky3ruiCW8HwbbidLX/BrN3vqw3O3NiHcY/KOt2KSpJNFFzQ3dbgO0GijaUb0QLa/VSYS2kpJuttRHbOok7tUqq6txPIgknYok8RSXL07Cn+u2TSsxhKpBcyg6zH8tPs/xmOd8jo3lR6CYGJkkZIgqZ386PwTQ7W5i9j7JBk4RzkJC6EDJX6FFJzfxj0dbfZ8KQ22jdT1iEKLr8D4L5rcJL+KnziOa+kyNSfIMqi9CSiZSIYm2i27I7LEfkkECG+QftyjgcdD8oPcwHtVZM46kLaOsYbQmzeFzuuE+Bn+Co0LAmlqJUcWqTdL0VS4BFilYML2JJnoMRSnLIsIRh9sSGjQ+j9sB3rJH9yfIgy5zeHlarKFPpb0REKoEycRN97ioR89AoyCHqt1m+4b+FJFyYHYPARo4rucBtIyMPv23HKkdTlw5TY1nCn5aLy+BVAjKFVmAesOanXavWij6JAauSozXLW1QCPmduTNpYQr++dDgjarbFfH9EGC2vQFYacpxk1fEc1++caIH7hs5fn6KFQbChulJ7OCnMdcoRgymVssdd2t8="
