language: ruby
branches:
  only:
    - main
before_script:
  - chmod +x deploy.sh
script:
  - bundle exec jekyll build
  - "./deploy.sh"
env:
  global:
    secure: "sMpyFbSpDSD3SBIeDiYEVULr6WKBz22h11ZZnidijvDKdgXquUD345gRfv8dM5p3ft6pzLdv3QriIlHp3/g7/e9/QTuOwAUUAxYH1hP5dS2Vq9t54GwNa/svGvLFn7HBjnZPfQqwryYmtbAUU1kdp/aOsVZE6yVDr12gWSTPB1dixKC+XmqAg2ctws2+/8Gk1xVjtxuN3PTzZlTEuBeJRlqCgI6OMUDJtEuf5SGDfX01FR4NwXWYjK9+ro/gC6FpB66Uj3Rc1MUnIMK5+6m0g0dEEaxLYCLgq8d8a6ST4zeo3FahJmjy5orWfzhMYfIezTtPnh/3YSHz1jrft8vKb58pZm9AmH457BIxiHkSA63Tz4HSoOhb6rMndVLM9dM91Zvbf3JYNuTR5DGnNtc/GJazB5/2qL4RTsqQteoHdsX18NXZsWjunPfgWLGPRmqVi4DW3265zu+qz/6vqublUc1Xm9XuTU/MCfr9VFezgpbtBG69EnPjCIsgby7wU4b57j0jnLTn1bdPPDs/N5qFEfL/7GWll7Wn7Mjy8dfrEoxzFnJA3DI4HpFePQBTZMMiRdorIxhvRGkse6tEpmvbQ0tt/WYhLgyBbA6AyfTBgfgWtQxNxR0npWxHceBdqr+eoAVyvdgPbvbHUsn5lG/9se7J+Yd5VzqvSRB/aGXjMCk="