language: ruby
branches:
  only:
    - master
before_script:
  - chmod +x deploy.sh
script:
  - bundle exec jekyll build
  - "./deploy.sh"
env:
  global:
    secure: Wtzo/807ansxq+NnirmNvK9bDxkTzpk6yo8m4W45XU9KBha6hcD1zQNRSTHQja1hE2QATK+EoShY8XCEX+4nELIuLMN7qCGOHXH8WERehOOMnzfKdYUpkUzondqMjDECRYln+vZeje7noeWwHak8hG6Vwxte5dpxNmOxjoQWr2oyQa/SY6z4vFQb56f5YDbAXWTGHh4lcI4kld9/cY9nW/d+UGv9A1Tu/yKNEzxSvhsznKYSyymOm/yRV2JxRHzAP+jj194q2GK5oMOrrGjO2wJtyQN/b0e95icntELhpbKHhMrs+EsZB70yFd37E9RMk7QSnjEcaCiAG2dP/1v2zOifeja8Rwnv8Tbmdeg/DzP82mSstywo4X3i/q6MGOkSVy9wd/trG3+2CX+6wKFMhqsoyXkWiX3U1WrIHRIZicJRh1Wx6W3ReRVv4erpI107801vYNMr1PSwMthBetJs+z1ltpyIVPC6EAvEBN1TddPmYaNHuIubtLzv1Qst3sWZh1C6NJgG2er+ZtBNAtLsuceDeReDTVVIfPeEa+iFRKDXKTUtDySuLjlG58ld8t43/HzoJ82fc0UG7Lif0+hQGWWp916uS44b1B+PzsC+9tC1YoUeuhRsx01wz1O3Z2l9E8xmsvHPMciHtMw6E+i9LmQPaZDuxjBReWb2HvkkcsE=
