language: ruby
branches:
  only:
    - main
before_script:
  - chmod +x deploy.sh
script:
  - bundle exec jekyll build
  - "./deploy.sh"
env:
  global:
    secure: N38HNlsIZ/bG6qF5s/a492m6soGP9k7EjSTDjmbDbXUrklyNL6M8LCyTuAEfkJ75TFdWCErTSBbiCzYivioUAStxuEfXEl+/rUE2SRxuszc7ehN0KqUImQRqfrjlbH+/TEZCKuGRdZuIkhF1PeZFIGV7TNqblJuFt91AeOvzu3L8kJt0mWJFvlkAyOnbsFmADMcm1XiUnZRIn3CmsqIYSAAL+mfsF6Rgn/tHE2mUZ+z2BdimgfjKmkRhJjGUMCjbeodH9Gq8GNhzcJp78g8ipkRv79Y0YfnOHNDLZ6KcrzEs8Sz2GqGN7hY9nQsLPSCxLPF+GmoBG98cFm05y/KcoavmvJmKDA09hfB0fb5eCbUbuO1bBshmHukZs+gqmoeEppRnnyecPIUe98nxf5GeoxmZCkuBspapths6aghNsJRMR5H4eSUxeCfVKlqtep3qtnyLPVv4LItqrr0UdzeuVY/icb+vuAZGxCpUnN2igv5sKemaHC59uz8c5uFYwfQcKToBbe97pH7Wot05FSpuGgub48ONOHheVWHQ3vXWmvrfjWvVzfeRFAn9CwJ4bZ/6hDSGvZM+NyBactxVtOF2C0uxMlyrLT3N1no5IpgibrOgOYwPHwTHJEyhiyTRh1a631AAjPHymBgKWIJoVm3uSQKhFpaeIH7lOgrxFGqR458=